M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Wed 10 Jan 2024 03:32:59 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-10T15:32:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X3.4073Y-3.4254
T2
X3.3525Y-4.574
M30
